version: '3.7'

services:
  mongo_container:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - ./mongo/dump/mydb:/dump
      - ./mongo/import.sh:/docker-entrypoint-initdb.d/import.sh
    restart: on-failure
    networks:
      - app
  backend:
    build: ./backend
    depends_on:
      - mongo_container
    restart: on-failure
    command: sh -c '/app/wait-for-it.sh -t 0 mongo_container:27017 -- npm run start'
    networks:
      - app
    ports:
      - "3001:3001"
  # frontend:
  #   build: ./frontend
  #   restart: on-failure
  #   depends_on:
  #     - backend
  #     - mongo_db
  #   ports:
  #     - 4200:4200
  #   networks:
  #     - app

networks:
  app:
